In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/home/mike/Downloads/data/archive(15)/heart.csv")

In [3]:
data.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trtbps    303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalachh  303 non-null    int64  
 8   exng      303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64  
 11  caa       303 non-null    int64  
 12  thall     303 non-null    int64  
 13  output    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [5]:
print(data.index) # they are attributes not functions
print(data.shape)

RangeIndex(start=0, stop=303, step=1)
(303, 14)


In [6]:
pd.set_option('display.max_columns',85)
pd.set_option('display.max_rows',200)

In [7]:
data

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [8]:
type(data['age'])

pandas.core.series.Series

In [9]:
data.sex

0      1
1      1
2      0
3      1
4      0
      ..
298    0
299    1
300    1
301    1
302    0
Name: sex, Length: 303, dtype: int64

In [10]:
data['sex']

0      1
1      1
2      0
3      1
4      0
      ..
298    0
299    1
300    1
301    1
302    0
Name: sex, Length: 303, dtype: int64

In [11]:
data[['sex','age']]

sex  age
0      1   63
1      1   37
2      0   41
3      1   56
4      0   57
..   ...  ...
298    0   57
299    1   45
300    1   68
301    1   57
302    0   57

[303 rows x 2 columns]

In [12]:
data.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [13]:
data.iloc[0] # first row series

age          63.0
sex           1.0
cp            3.0
trtbps      145.0
chol        233.0
fbs           1.0
restecg       0.0
thalachh    150.0
exng          0.0
oldpeak       2.3
slp           0.0
caa           0.0
thall         1.0
output        1.0
Name: 0, dtype: float64

In [14]:
data.iloc[[0,1]] # the first two rows

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   

   caa  thall  output  
0    0      1       1  
1    0      2       1

In [15]:
data.iloc[[1,2],[1,3]]

sex  trtbps
1    1     130
2    0     130

In [16]:
data.loc[[1,2],'age']

1    37
2    41
Name: age, dtype: int64

In [17]:
data.loc[[1,2],['age','chol']]

age  chol
1   37   250
2   41   204

In [18]:
data['fbs'].value_counts()

0    258
1     45
Name: fbs, dtype: int64

In [19]:
data.loc[0:2,'age':'fbs']

age  sex  cp  trtbps  chol  fbs
0   63    1   3     145   233    1
1   37    1   2     130   250    0
2   41    0   1     130   204    0

#### indexes

In [20]:
# data.set_index("age", inplace="True") set age as the index

In [21]:
# data.loc["corey shaffer"] just an example

In [22]:
# data.loc[0] this will give an error

In [23]:
# data.reset_index(inplace=True) to reset the index

In [24]:
# data = pd.read_csv("location",index_col="respondeent") setting the index while loading the data

In [25]:
# data.sort_index(ascending = False, inplace=True) # sort the index in descending order

In [52]:
print('Task 43:') 
df = pd.DataFrame({
    'a' : [1,2,3,4], 
    'b' : [9,8,7,6],
    'c' : [11,12,13,14]
})
print(df) 

print('changing on one column')
# Change columns
df.loc[df.a >= 2,'b'] = 9
print(df)

Task 43:
   a  b   c
0  1  9  11
1  2  8  12
2  3  7  13
3  4  6  14
changing on one column
   a  b   c
0  1  9  11
1  2  9  12
2  3  9  13
3  4  9  14


In [53]:
df.loc[df.c<=29,'b']=100 # Change columns based on other columns 

In [54]:
print(df)

   a    b   c
0  1  100  11
1  2  100  12
2  3  100  13
3  4  100  14


In [56]:
# changing multile columns based on one column
df.loc[df.a<=5,['a','b','c']]=100

In [57]:
df

a    b    c
0  100  100  100
1  100  100  100
2  100  100  100
3  100  100  100

In [58]:
# pandas mask
df_mask = pd.DataFrame({
    'a' : [True] * 4, 
    'b' : [False] * 4,
    'c' : [True, False] * 2
})

In [59]:
df_mask

a      b      c
0  True  False   True
1  True  False  False
2  True  False   True
3  True  False  False

In [60]:
print(df.where(df_mask,-1000))

     a     b     c
0  100 -1000   100
1  100 -1000 -1000
2  100 -1000   100
3  100 -1000 -1000


In [66]:
import numpy as np
df['logic'] = np.where(df['a']<=5,'high','low') #Check high or low comparing the column against 5
df

a    b    c logic
0  100  100  100   low
1  100  100  100   low
2  100  100  100   low
3  100  100  100   low

In [69]:
print('Task 47:')
marks_df = pd.DataFrame({
    'Language' : [60, 45, 78, 4], 
    'Math' : [90, 80, 23, 60],
    'Science' : [45, 90, 95, 20]
});
print(marks_df)
marks_df['language_grade'] = np.where(marks_df['Language'] >= 50, 'Pass', 'Fail')
marks_df['math_grade'] = np.where(marks_df['Math'] >= 50, 'Pass', 'Fail')
marks_df['science_grade'] = np.where(marks_df['Science'] >= 50, 'Pass', 'Fail')
print("marks with grades\n",marks_df)

Task 47:
   Language  Math  Science
0        60    90       45
1        45    80       90
2        78    23       95
3         4    60       20
marks with grades
    Language  Math  Science language_grade math_grade science_grade
0        60    90       45           Pass       Pass          Fail
1        45    80       90           Fail       Pass          Pass
2        78    23       95           Pass       Fail          Pass
3         4    60       20           Fail       Pass          Fail


In [75]:
# printing only the marks with pass in language
marks_passed = marks_df[marks_df.Language>=50]
marks_passed

Language  Math  Science language_grade math_grade science_grade
0        60    90       45           Pass       Pass          Fail
2        78    23       95           Pass       Fail          Pass

In [78]:
# printing only the marks with pass in language and maths
marks_lm = marks_df[(marks_df.Language>=50) & (marks_df.Math>=50)]
marks_lm

Language  Math  Science language_grade math_grade science_grade
0        60    90       45           Pass       Pass          Fail

In [79]:
print('Task 51:')
stars = {
    'age' : [31, 23, 65, 50],
    'movies' : [51, 23, 87, 200],
    'awards' : [42, 12, 4, 78]
    }
star_names = ['dhanush', 'simbu', 'kamal', 'vikram']
stars_df = pd.DataFrame(data=stars, index=[star_names])
print(stars_df)

Task 51:
         age  movies  awards
dhanush   31      51      42
simbu     23      23      12
kamal     65      87       4
vikram    50     200      78


In [80]:
stars_df.iloc[1:3]

age  movies  awards
simbu   23      23      12
kamal   65      87       4

In [81]:
print('Task 53:')  
numbers = pd.DataFrame({
        'one' : [10, 50, 80, 40],
        'two' : [2, 6, 56, 45]
    },
    index = [12, 14, 16, 18])
print(numbers)

print('label between 12 and 16')
print(numbers.loc[12:16])

print('index between 1 and 3')
print(numbers.iloc[1:3])

Task 53:
    one  two
12   10    2
14   50    6
16   80   56
18   40   45
label between 12 and 16
    one  two
12   10    2
14   50    6
16   80   56
index between 1 and 3
    one  two
14   50    6
16   80   56


In [82]:
print('Task 55:')

age_movies_25 = stars_df[(stars_df.movies > 25 ) & (stars_df.age > 25)]  
print(age_movies_25)

Task 55:
         age  movies  awards
dhanush   31      51      42
kamal     65      87       4
vikram    50     200      78


In [85]:
custom_stars = stars_df[stars_df.age.isin([31,65])] #Stars in in certain ages 
custom_stars

age  movies  awards
dhanush   31      51      42
kamal     65      87       4

In [87]:
not_in = stars_df[~(stars_df.age.isin([31,65]))] #Stars not in certain ages 
not_in

age  movies  awards
simbu    23      23      12
vikram   50     200      78

In [90]:
# apply custom function

def GrowUp(x):
    avg_weight =  sum(x[x['size'] == 'series1'].weight * 1.5)
    avg_weight += sum(x[x['size'] == 'M'].weight * 1.25)
    avg_weight += sum(x[x['size'] == 'L'].weight)
    avg_weight /= len(x)
    return pd.Series(['L',avg_weight,True], index=['size', 'weight', 'adult'])

animals_df = pd.DataFrame({'animal': 'cat dog cat fish dog cat cat'.split(),
                   'size': list('SSMMMLL'),
                   'weight': [8, 10, 11, 1, 20, 12, 12],
                   'adult' : [False] * 5 + [True] * 2})

gb = animals_df.groupby(['animal'])

expected_df = gb.apply(GrowUp)
print(animals_df)
print(expected_df)

  animal size  weight  adult
0    cat    S       8  False
1    dog    S      10  False
2    cat    M      11  False
3   fish    M       1  False
4    dog    M      20  False
5    cat    L      12   True
6    cat    L      12   True
       size   weight  adult
animal                     
cat       L   9.4375   True
dog       L  12.5000   True
fish      L   1.2500   True


In [92]:
print('Task 59:')
weights = animals_df.groupby(['weight']).get_group(12)  
print(weights)

Task 59:
  animal size  weight  adult
5    cat    L      12   True
6    cat    L      12   True


In [93]:
# Creating new Columns using Applymap
# Sides & applymap 

print('Task 60:')
sides_df = pd.DataFrame({
    'a' : [1, 1, 2, 4],
    'b' : [2, 1, 3, 4]
    })  
print(sides_df)
source_cols = sides_df.columns
print(source_cols)
new_cols = [str(x)+"_side" for x in source_cols]
side_category = {
    1 : 'North',
    2 : 'East',
    3 : 'South', 
    4 : 'West'
    }
sides_df[new_cols] = sides_df[source_cols].applymap(side_category.get)
print(sides_df)

Task 60:
   a  b
0  1  2
1  1  1
2  2  3
3  4  4
Index(['a', 'b'], dtype='object')
   a  b a_side b_side
0  1  2  North   East
1  1  1  North  North
2  2  3   East  South
3  4  4   West   West


In [94]:

# Replacing some values with mean of the rest of a group 
print('Task 61:')  
df = pd.DataFrame({'A' : [1, 1, 2, 2], 'B' : [1, -1, 1, 2]})
print(df)

gb = df.groupby('A')

def replace(g):
    mask = g < 0
    g.loc[mask] = g[~mask].mean()
    return g

gbt = gb.transform(replace)

print(gbt)

Task 61:
   A  B
0  1  1
1  1 -1
2  2  1
3  2  2
     B
0  1.0
1  1.0
2  1.0
3  2.0


In [96]:

# argsort
# Select rows with data closest to certain value using argsort 
print('Task 64:')  
df = pd.DataFrame({
    "a": np.random.randint(0, 100, size=(5,)), 
    "b": np.random.randint(0, 70, size=(5,))
})
print(df)
par = 65
print('with argsort')
df1 = df.loc[(df.a-par).abs().argsort()]
print(df1)

print(df.loc[(df.b-2).abs().argsort()])

Task 64:
    a   b
0  44  54
1  92  44
2  18   0
3  27  12
4  20  25
with argsort
    a   b
0  44  54
1  92  44
3  27  12
4  20  25
2  18   0
    a   b
2  18   0
3  27  12
4  20  25
1  92  44
0  44  54


In [100]:

# argsort with stars
# old stars (near by 50 age) argsort 
print('Task 65:')  
stars = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "movies": [2, 3, 90, 45, 34, 2] 
})
print(stars.loc[(stars.age - 50).abs().argsort()])

Task 65:
   age  movies
1   50       3
3   45      45
4   65      34
2   24      90
5   18       2
0   17       2


In [105]:
import functools
print('Task 67:')
stars = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "movies": [22, 33, 90, 75, 34, 2] 
})  
print(stars)
print('Young and more movies acted')
young = stars.age < 30    
print("young\n\n",type(young))
more_movies = stars.movies > 30
young_more = [young, more_movies]
young_more_Criteria = functools.reduce(lambda x, y : x & y, young_more)
print(stars[young_more_Criteria])

Task 67:
   age  movies
0   17      22
1   50      33
2   24      90
3   45      75
4   65      34
5   18       2
Young and more movies acted
young

 <class 'pandas.core.series.Series'>
   age  movies
2   24      90


In [106]:
print('Task 69:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees.rename(columns={'age': 'User Age', 'salary': 'Salary 2018'}, inplace=True)
print(employees)

Task 69:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   User Age  Salary 2018  grade
0        17           75      7
1        50           33      8
2        24           90      9
3        45          175      2
4        65          134      7
5        18           78      8


In [107]:
# adding a new column
print('Task 70:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)

Task 70:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade     group
0   17      75      7 -0.138280
1   50      33      8 -1.470184
2   24      90      9  1.108995
3   45     175      2  1.089966
4   65     134      7 -0.985166
5   18      78      8 -0.619781


In [109]:
# drop a column
print('Task 71:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)
employees.drop(employees.columns[[0]], axis=1, inplace = True)
print(employees)

Task 71:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade     group
0   17      75      7  0.581870
1   50      33      8 -1.330991
2   24      90      9 -0.398049
3   45     175      2 -1.265309
4   65     134      7  0.582696
5   18      78      8 -0.358846
   salary  grade     group
0      75      7  0.581870
1      33      8 -1.330991
2      90      9 -0.398049
3     175      2 -1.265309
4     134      7  0.582696
5      78      8 -0.358846


In [110]:
# Drop multiple columns 
print('Task 72:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8] 
})  
print(employees)
employees['group'] = pd.Series(np.random.randn(len(employees)))
print(employees)
employees.drop(employees.columns[[1, 2]], axis=1, inplace = True)
print(employees)

Task 72:
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
   age  salary  grade     group
0   17      75      7 -0.321112
1   50      33      8 -1.346738
2   24      90      9 -0.696919
3   45     175      2 -0.634617
4   65     134      7 -1.382753
5   18      78      8 -0.697167
   age     group
0   17 -0.321112
1   50 -1.346738
2   24 -0.696919
3   45 -0.634617
4   65 -1.382753
5   18 -0.697167


In [111]:
# drop the first and last column
print('Task 73:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)
employees.drop(employees.columns[[0, len(employees.columns)-1]], axis=1, inplace = True)
print(employees)

Task 73:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
   salary  grade
0      75      7
1      33      8
2      90      9
3     175      2
4     134      7
5      78      8


In [112]:
#Delete by pop function  
print('Task 74:')  
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)
group = employees.pop('group')
print(employees)
print(group)

Task 74:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
   age  salary  grade
0   17      75      7
1   50      33      8
2   24      90      9
3   45     175      2
4   65     134      7
5   18      78      8
0    1
1    1
2    2
3    2
4    2
5    1
Name: group, dtype: int64


In [115]:
# #DataFrame.from_items 
# print('Task 75:')  
# df = pd.DataFrame.from_items([('A', [1, 2, 3]), ('B', [4, 5, 6]), ('C', [7,8, 9])], orient='index', columns=['one', 'two', 'three'])
#/print(df) # throwing error

In [116]:
#Pandas to list 
print('Task 76:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list1 = list(employees.columns.values) 
employees_list2 = employees.values.tolist()
#employees_list = list(employees)
print(employees_list1)
print(employees_list2)

Task 76:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
['age', 'salary', 'grade', 'group']
[[17, 75, 7, 1], [50, 33, 8, 1], [24, 90, 9, 2], [45, 175, 2, 2], [65, 134, 7, 2], [18, 78, 8, 1]]


In [117]:
#Pandas rows to list
print('Task 77:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = employees.values.tolist()
print(employees_list2)
print(type(employees_list2))
print(len(employees_list2))

Task 77:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
[[17, 75, 7, 1], [50, 33, 8, 1], [24, 90, 9, 2], [45, 175, 2, 2], [65, 134, 7, 2], [18, 78, 8, 1]]
<class 'list'>
6


In [118]:
#Pandas rows to map 
print('Task 79:')
employees = pd.DataFrame({
    "age": [17, 50, 24, 45, 65, 18], 
    "salary": [75, 33, 90, 175, 134, 78],
    "grade" : [7, 8, 9, 2, 7, 8],
    "group" : [1, 1, 2, 2, 2, 1] 
    
})  
print(employees)  
employees_list2 = map(list, employees.values)
print(employees_list2)
print(type(employees_list2))

Task 79:
   age  salary  grade  group
0   17      75      7      1
1   50      33      8      1
2   24      90      9      2
3   45     175      2      2
4   65     134      7      2
5   18      78      8      1
<class 'map'>


In [119]:
# drop duplicates
print('Task 81:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users.drop_duplicates('id', inplace=True, keep='last')
print(users)

Task 81:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id      city  count
1   1  Montreal      8
3   2  Montreal      2
5   3    Ottawa      8


In [122]:
#Selecting multiple columns 
print('Task 82:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)
users1 = users[['id', 'city']]
print(users1)

Task 82:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id      city
0   1   Toronto
1   1  Montreal
2   2   Calgary
3   2  Montreal
4   3  Montreal
5   3    Ottawa


In [124]:
#Selecting multiple columns 
print('Task 83:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
}) 
print(users)
columns = ['id', 'count']
users1 = pd.DataFrame(users, columns=columns)
print(users1)

Task 83:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
   id  count
0   1      7
1   1      8
2   2      9
3   2      2
4   3      7
5   3      8


In [125]:
# row and column slicing
print('Task 84:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
users1 = users.iloc[0:2, 1:3]
print(users1)

Task 84:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
       city  count
0   Toronto      7
1  Montreal      8


In [126]:
# iterating rows
print('Task 85:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for index, row in users.iterrows():
    print(row['city'], "==>", row['count'])

Task 85:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
Toronto ==> 7
Montreal ==> 8
Calgary ==> 9
Montreal ==> 2
Montreal ==> 7
Ottawa ==> 8


In [127]:
# iterating duplicates
print('Task 86:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for row in users.itertuples(index=True, name='Pandas'):
    print(getattr(row, 'city'))
    
for row in users.itertuples(index=True, name='Pandas'):
    print(row.count)

Task 86:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
Toronto
Montreal
Calgary
Montreal
Montreal
Ottawa
7
8
9
2
7
8


In [128]:
#iterating rows and columns
print('Task 87:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)    
for i, row in users.iterrows():
    for j, col in row.iteritems():    
        print(col)

Task 87:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
1
Toronto
7
1
Montreal
8
2
Calgary
9
2
Montreal
2
3
Montreal
7
3
Ottawa
8


In [129]:

# List of Dictionary to Dataframe 
print('Task 88:')  
pointlist = [
                {'points': 50, 'time': '5:00', 'year': 2010}, 
                {'points': 25, 'time': '6:00', 'month': "february"}, 
                {'points':90, 'time': '9:00', 'month': 'january'}, 
                {'points_h1':20, 'month': 'june'}
            ]
print(pointlist)
pointDf = pd.DataFrame(pointlist)
print(pointDf)

pointDf1 = pd.DataFrame.from_dict(pointlist)
print(pointDf1)

Task 88:
[{'points': 50, 'time': '5:00', 'year': 2010}, {'points': 25, 'time': '6:00', 'month': 'february'}, {'points': 90, 'time': '9:00', 'month': 'january'}, {'points_h1': 20, 'month': 'june'}]
   points  time    year     month  points_h1
0    50.0  5:00  2010.0       NaN        NaN
1    25.0  6:00     NaN  february        NaN
2    90.0  9:00     NaN   january        NaN
3     NaN   NaN     NaN      june       20.0
   points  time    year     month  points_h1
0    50.0  5:00  2010.0       NaN        NaN
1    25.0  6:00     NaN  february        NaN
2    90.0  9:00     NaN   january        NaN
3     NaN   NaN     NaN      june       20.0


In [130]:
# NaN values 
print('Task 89:')
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
df1 = df.isnull()
print(df1)

Task 89:
          0         1         2         3         4         5
0 -0.795608 -0.218048 -2.299574 -0.063416  0.201676  1.487427
1 -0.018720       NaN -0.037363  0.190242 -0.875129 -0.318767
2 -0.306797       NaN -0.278133 -0.521877 -0.507999 -0.869195
3  0.992874  0.280981  0.572636 -0.238188  0.215281  0.090849
4 -0.139837 -0.632727 -1.232010 -1.532464  0.058471 -2.788477
5 -0.113330  0.235060 -0.318397       NaN  0.565844 -0.251242
6 -0.257135 -0.348884  1.664999  0.317203 -1.169490 -0.310805
7 -1.708051  0.022510 -0.659043 -0.155393  0.337401       NaN
8  0.660895  0.240909 -0.223281  0.309016 -1.554320       NaN
9  2.382233  0.154918  0.329649 -1.430126 -0.801443 -0.405395
       0      1      2      3      4      5
0  False  False  False  False  False  False
1  False   True  False  False  False  False
2  False   True  False  False  False  False
3  False  False  False  False  False  False
4  False  False  False  False  False  False
5  False  False  False   True  False  False
6

In [131]:
# Sum of all nan
print('Task 90:')  
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum())
print(df.isnull().sum(axis=1))
print(df.isnull().sum().tolist())

Task 90:
          0         1         2         3         4         5
0 -0.262524  0.225402 -0.835328  0.247587  1.653468  0.537966
1 -0.788959       NaN -0.317431 -0.648925  1.564013 -0.040596
2 -1.299400       NaN -0.679061 -0.755961 -0.448051  0.796036
3 -0.065757  0.203695  0.007027 -1.349046 -0.093934 -0.950031
4 -1.072987 -0.043903 -1.472045 -1.677248 -0.799731 -0.326198
5  1.963135  0.467580  0.657272       NaN -0.171338 -2.354219
6  1.388529  0.343820 -1.271599 -0.660539  0.518711  0.374874
7 -1.129184  0.786992  0.575432  0.076285  0.954202       NaN
8  1.455456 -0.499772  0.087342 -0.395972  0.356259       NaN
9  1.339107  0.442277  1.325566 -0.848955  0.421525 -1.076845
0    0
1    2
2    0
3    1
4    0
5    2
dtype: int64
0    0
1    1
2    1
3    0
4    0
5    1
6    0
7    1
8    1
9    0
dtype: int64
[0, 2, 0, 1, 0, 2]


In [132]:
# Sum of all nan rowwise 
print('Task 91:')  
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum(axis=1))

Task 91:
          0         1         2         3         4         5
0 -0.597121  0.711550 -0.097996 -0.961068 -0.226037 -0.587204
1 -1.927100       NaN -0.368427  0.472147  0.380132  0.271820
2 -0.595551       NaN  0.407085  0.117660 -0.432303  0.019792
3 -0.454863 -0.621776 -0.073298 -0.083654 -0.971213  0.532511
4 -1.003663  0.889402 -0.713239 -0.133077 -1.621471  1.329467
5 -0.457202 -0.308728  0.106695       NaN  0.753788 -0.106249
6 -1.593942  2.618269 -0.594499  0.414286  0.006421 -0.623238
7  0.069892  1.127361  1.824879  0.034673 -0.492967       NaN
8  2.116715  0.107883  1.357592  1.263986  0.996686       NaN
9  0.745108  0.137637 -0.893686  1.505271  1.627263  1.405654
0    0
1    1
2    1
3    0
4    0
5    1
6    0
7    1
8    1
9    0
dtype: int64


In [133]:
# Sum of all nan as list 
print('Task 92:')  
df = pd.DataFrame(np.random.randn(10,6))
# Make a few areas have NaN values
df.iloc[1:3,1] = np.nan
df.iloc[5,3] = np.nan
df.iloc[7:9,5] = np.nan
print(df)
print(df.isnull().sum().tolist())

Task 92:
          0         1         2         3         4         5
0 -0.804443  0.313104 -0.738200  0.393116  1.583913  0.305910
1 -0.221103       NaN  0.607422  0.693134  0.257217  0.098293
2 -1.431913       NaN  0.321431 -0.699130  0.090197  0.916744
3 -2.686857 -0.080871 -2.322682 -0.952824  0.047704 -1.583394
4 -0.748688 -0.441280 -0.978482 -0.661462  1.792438  1.258394
5  1.124678  0.149854  0.857205       NaN  0.015672 -0.145841
6 -0.919837  0.217553 -0.604249  0.473200  0.426765  0.091264
7  0.797994  0.805894  0.249693  1.500301  1.472804       NaN
8  0.233363 -0.296092  0.063843  0.009606  2.954072       NaN
9  0.371451 -0.965856 -0.004806  0.347659 -1.106308  0.240925
[0, 2, 0, 1, 0, 2]


In [134]:
# Change the order of columns 
print('Task 93:')  
users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 
print(users)

# below line throws error
# users1 = users.reindex_axis(['city', 'count', 'id'], axis=1)
# print(users1)

users2 = users.reindex(columns=['city', 'id', 'count'])
print(users2)

Task 93:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8
       city  id  count
0   Toronto   1      7
1  Montreal   1      8
2   Calgary   2      9
3  Montreal   2      2
4  Montreal   3      7
5    Ottawa   3      8


In [135]:
# Drop multiple rows
print('Task 94:')
numbers = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6], 
    "number": [10, 20, 30, 30, 23, 12]
    
})  
print(numbers)
numbers.drop(numbers.index[[0, 3, 5]], inplace=True)
print(numbers)

Task 94:
   id  number
0   1      10
1   2      20
2   3      30
3   4      30
4   5      23
5   6      12
   id  number
1   2      20
2   3      30
4   5      23


In [136]:
# Drop multiple rows by row name 
print('Task 95:')  
numbers = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6], 
    "number": [10, 20, 30, 30, 23, 12]
    
}, index=['one', 'two', 'three', 'four', 'five', 'six'])  
print(numbers)
numbers1 = numbers.drop(['two','six'])
print(numbers1)
numbers2 = numbers.drop('two')
print(numbers2)

Task 95:
       id  number
one     1      10
two     2      20
three   3      30
four    4      30
five    5      23
six     6      12
       id  number
one     1      10
three   3      30
four    4      30
five    5      23
       id  number
one     1      10
three   3      30
four    4      30
five    5      23
six     6      12


In [137]:
# Get group 
print('Task 96:')
cats = animals_df.groupby(['animal']).get_group('cat')
print(cats)

Task 96:
  animal size  weight  adult
0    cat    S       8  False
2    cat    M      11  False
5    cat    L      12   True
6    cat    L      12   True


In [139]:
import numpy

In [140]:
# Get the the odd row 
print('Task 97:')  
x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[::2])

Task 97:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [141]:
# Get the even columns 
print('Task 98:')  
x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[:, 1::2])

Task 98:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


In [143]:
# Odd rows and even columns
print('Task 99:')  

x = numpy.array([
                    [ 1,  2,  3,  4,  5],
                    [ 6,  7,  8,  9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20]
                ]
    )
print(x)
print(x[::2, 1::2])

Task 99:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 2  4]
 [12 14]]


In [144]:
# Basic group by 
print('Task 102:')
animals_df1 = animals_df.groupby('animal').apply(lambda x: x['size'][x['weight'].idxmax()])
print(animals_df1)

Task 102:
animal
cat     L
dog     M
fish    M
dtype: object


In [152]:
# Missing Data: Make A'th 3rd coulmn Nan 

print('Task 103:')  
df = pd.DataFrame(np.random.randn(6,1), index=pd.date_range('2013-08-01', periods=6, freq='B'), columns=list('A'))
print(df)
df.loc[df.index[3], 'A'] = np.nan
print(df)

Task 103:
                   A
2013-08-01  0.396887
2013-08-02  1.612440
2013-08-05 -0.957986
2013-08-06 -0.486112
2013-08-07 -0.961876
2013-08-08  2.159719
                   A
2013-08-01  0.396887
2013-08-02  1.612440
2013-08-05 -0.957986
2013-08-06       NaN
2013-08-07 -0.961876
2013-08-08  2.159719


In [153]:
# reindex
print('Task 104:')
df1 = df.reindex(df.index[::-1]).ffill()
print(df1)

Task 104:
                   A
2013-08-08  2.159719
2013-08-07 -0.961876
2013-08-06 -0.961876
2013-08-05 -0.957986
2013-08-02  1.612440
2013-08-01  0.396887


In [155]:
# 106. Change columns
print('Task 106:')

users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa']
}) 

print('Before changing columns : ')
print(users)

# change columns
users_new = users.rename({'name': 'first_name', 'city': 'current_city'}, axis = 1)

print('\nAfter changing columns : ')
print(users_new)

Task 106:
Before changing columns : 
    name      city
0  kevin   Toronto
1  james  Montreal
2  kumar   Calgary
3  kevin  Montreal
4  kevin  Montreal
5  james    Ottawa

After changing columns : 
  first_name current_city
0      kevin      Toronto
1      james     Montreal
2      kumar      Calgary
3      kevin     Montreal
4      kevin     Montreal
5      james       Ottawa


In [156]:
# 107. Match with isin function

print('Task 107:')

users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa']
}) 

print('Original Dataframe:')
print(users)

print('\nFinding `Montreal` in by using isin function :')

users.isin(['Montreal']).any()

Task 107:
Original Dataframe:
    name      city
0  kevin   Toronto
1  james  Montreal
2  kumar   Calgary
3  kevin  Montreal
4  kevin  Montreal
5  james    Ottawa

Finding `Montreal` in by using isin function :


name    False
city     True
dtype: bool

In [157]:
# 108. Finding specific items by using `isin` function

print('Task 108:')

users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa']
}) 

print('Original Dataframe: ')
print(users)

print('\nFinding `Montreal` in using isin and stack them: ')
print(users[users.isin(['Montreal'])].stack())

Task 108:
Original Dataframe: 
    name      city
0  kevin   Toronto
1  james  Montreal
2  kumar   Calgary
3  kevin  Montreal
4  kevin  Montreal
5  james    Ottawa

Finding `Montreal` in using isin and stack them: 
1  city    Montreal
3  city    Montreal
4  city    Montreal
dtype: object


In [158]:
# 109. Exclude specific matching

print('Task 109:')

users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa']
}) 

print('Original Dataframe: ')
print(users)

print('\nExcluding `Montreal` in using isin and stack them: ')
print(users[~users.isin(['Montreal'])].stack())

Task 109:
Original Dataframe: 
    name      city
0  kevin   Toronto
1  james  Montreal
2  kumar   Calgary
3  kevin  Montreal
4  kevin  Montreal
5  james    Ottawa

Excluding `Montreal` in using isin and stack them: 
0  name      kevin
   city    Toronto
1  name      james
2  name      kumar
   city    Calgary
3  name      kevin
4  name      kevin
5  name      james
   city     Ottawa
dtype: object


In [159]:
# 110. Apply a custom function on multiple columns

print('Task 110:')

amounts = pd.DataFrame({
    "CIBC": [200, 4200, 300, 300], 
    "TD": [1200, 800, 4000, 2000]
})

print('Original Dataframe: ')
print(amounts)

def get_total_amount(x):
    
    # if the amount is less than 500, skip it
    total_amount = 0
    
    if(x['CIBC'] > 499):
        total_amount += x['CIBC']
        
    if(x['TD'] > 499):
        total_amount += x['TD']
    
    return total_amount

amounts['Total'] = amounts.apply(get_total_amount, axis = 1)

print('Dataframe after applying the custom function: ')
print(amounts)

Task 110:
Original Dataframe: 
   CIBC    TD
0   200  1200
1  4200   800
2   300  4000
3   300  2000
Dataframe after applying the custom function: 
   CIBC    TD  Total
0   200  1200   1200
1  4200   800   5000
2   300  4000   4000
3   300  2000   2000


In [160]:
# 111. iterrows as tuples

print('Task 111:')

users = pd.DataFrame({
    "id": [1, 1, 2, 2, 3, 3], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 

print(users)  

print('\nIterate rows as tuples:')
for row in users.itertuples():
    print(row)

Task 111:
   id      city  count
0   1   Toronto      7
1   1  Montreal      8
2   2   Calgary      9
3   2  Montreal      2
4   3  Montreal      7
5   3    Ottawa      8

Iterate rows as tuples:
Pandas(Index=0, id=1, city='Toronto', count=7)
Pandas(Index=1, id=1, city='Montreal', count=8)
Pandas(Index=2, id=2, city='Calgary', count=9)
Pandas(Index=3, id=2, city='Montreal', count=2)
Pandas(Index=4, id=3, city='Montreal', count=7)
Pandas(Index=5, id=3, city='Ottawa', count=8)


In [163]:
# 112. Dataframe with NaN

print('Task 112:')

df = pd.DataFrame(np.nan, index = [0, 1, 2], columns = ['A', 'B', 'C'])

print(df)

Task 112:
    A   B   C
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN


In [164]:
# 113. Simple Dataframe with NaN

print('Task 113:')

df = pd.DataFrame([np.nan] * 5)

print(df)

Task 113:
    0
0 NaN
1 NaN
2 NaN
3 NaN
4 NaN


In [165]:
# 114. Pandas and Date with Range

print('Task 114:')

import datetime as dt

pd.np.random.seed(0)

df = pd.DataFrame({
     "date" : [dt.date(2012, x, 1) for x in range(1, 11)]
})

print(df)

Task 114:
         date
0  2012-01-01
1  2012-02-01
2  2012-03-01
3  2012-04-01
4  2012-05-01
5  2012-06-01
6  2012-07-01
7  2012-08-01
8  2012-09-01
9  2012-10-01


/home/mike/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  import sys


In [166]:
# 115. Pandas and Numpy Repeat

print('Task 115:')

df = pd.DataFrame({
     "entry" : np.repeat(3, 7) # Repeat the number for 7 times
})

print(df)

Task 115:
   entry
0      3
1      3
2      3
3      3
4      3
5      3
6      3


In [168]:
# 116. read_sql in Pandas

print('Task 116:')

# import sqlite3 as sql

# conn = sql.connect('/kaggle/input/rj-sample-datasets/sample.db')

# demo_df = pd.read_sql('SELECT ID, NAME FROM DEMO', conn)

# print(demo_df)

# # Note: online sqlite https://sqliteonline.com/

Task 116:


In [169]:
# 117. Get a single value by iat

print('Task 117:')

df = pd.DataFrame(np.random.randint(0, 100, size = (7, 2)), columns = list('ab'))

print('\nOriginal Dataframe:')
print(df)

val = df.iat[3, 1]

print('\nGetting value at 3rd row and first col:')
print(val)

Task 117:

Original Dataframe:
    a   b
0  44  47
1  64  67
2  67   9
3  83  21
4  36  87
5  70  88
6  88  12

Getting value at 3rd row and first col:
21


In [170]:
# 119. Add data one by one by using loc function

df = pd.DataFrame(columns = ['rows', 'cols', 'time taken'])

df.loc['Dataset1 - Dask'] = (1000, 20, 10)
df.loc['Dataset1 - Pandas'] = (1000, 20, 15)

df

rows cols time taken
Dataset1 - Dask    1000   20         10
Dataset1 - Pandas  1000   20         15

In [173]:
# # 122. Compare two dataframes

# df1 = pd.DataFrame({
#     'a' : [1,2,3], 
#     'b' : [9,8,7]
# })

# df2 = pd.DataFrame({
#     'a' : [1,1,3], 
#     'b' : [12,8,12]
# })

# print(df1.ompare(df2))

In [174]:
# 123. Difference between datetime by only seconds or dates

df1 = pd.to_datetime('2020-10-14 14:52:21')
df2 = pd.to_datetime('2020-10-18 15:58:10')

delta = (df2 - df1)

print('days   : ', delta.days)
print('seconds: ', delta.seconds)

days   :  4
seconds:  3949


In [175]:
# 125. Get dates and delta days in Dataframe

entries_count = 5

date_series = pd.Series(pd.date_range('2020-09-01', periods = entries_count, freq = 'D'))

time_delta_series = pd.Series([pd.Timedelta(days = i) for i in range(entries_count)])

df = pd.DataFrame({'entry_date': date_series, 'delta_days': time_delta_series})

print(df)

  entry_date delta_days
0 2020-09-01     0 days
1 2020-09-02     1 days
2 2020-09-03     2 days
3 2020-09-04     3 days
4 2020-09-05     4 days


In [176]:
# 126. Date addition with time delta

entries_count = 3

date_series = pd.Series(pd.date_range('2020-09-01', periods = entries_count, freq = 'D'))

time_delta_series = pd.Series([pd.Timedelta(days = i) for i in range(entries_count)])

df = pd.DataFrame({'entry_date': date_series, 'delta_days': time_delta_series})

print('\nBefore:')
print(df)


df['new_entry_date'] = df['entry_date'] + df['delta_days']
print('\nAfter:')
print(df)

print('\nData types:')
print(df.dtypes)


Before:
  entry_date delta_days
0 2020-09-01     0 days
1 2020-09-02     1 days
2 2020-09-03     2 days

After:
  entry_date delta_days new_entry_date
0 2020-09-01     0 days     2020-09-01
1 2020-09-02     1 days     2020-09-03
2 2020-09-03     2 days     2020-09-05

Data types:
entry_date         datetime64[ns]
delta_days        timedelta64[ns]
new_entry_date     datetime64[ns]
dtype: object


In [177]:
# 127. Converting Pandas innner list to numpy array without the word `list`

s = pd.Series([[1, 2, 3], np.array([1, 2, 3])])
    
print('Original Series:')
print(s)  

arr = np.array(s)
print('\nSeries to Array:')
print(arr)

print('\nAfter converting inner elements to list:')
x = np.array(s[:].tolist())
print(x)

Original Series:
0    [1, 2, 3]
1    [1, 2, 3]
dtype: object

Series to Array:
[list([1, 2, 3]) array([1, 2, 3])]

After converting inner elements to list:
[[1 2 3]
 [1 2 3]]


In [178]:
# 128. Append series to existing Dataframe

df = pd.DataFrame([1, 3, 4, 5], columns=["id"])
df.set_index("id")
print('Before:')
print(df)

marks = pd.Series([79, 20, 45, 99])
df["marks"] = marks
print('\nAfter:')
print(df)

Before:
   id
0   1
1   3
2   4
3   5

After:
   id  marks
0   1     79
1   3     20
2   4     45
3   5     99


In [179]:
# 129. Cumulative sum with group by with multiple values

df = pd.DataFrame({
    'City': ['Toronto', 'Toronto', 'Toronto', 'Montreal', 'Montreal', 'Montreal', 'New York', 'Toronto', 'New York', 'New York'], 
    'Year': [2020, 2020, 2018, 2018, 2018, 2012, 2012, 2012, 2016, 2018], 
    'Points': [1000, 2000, 3000, 3000, 2000, 1500, 1500, 500, 500, 300]
})

print('Before:')
print(df)

df.sort_values(['City', 'Year'], inplace=True)
print('\nAfter Sorting:')
print(df)

df['Points_cum'] = df.groupby(['City', 'Year'])['Points'].cumsum()
print('\nAfter Cumulative Sum:')
print(df)

Before:
       City  Year  Points
0   Toronto  2020    1000
1   Toronto  2020    2000
2   Toronto  2018    3000
3  Montreal  2018    3000
4  Montreal  2018    2000
5  Montreal  2012    1500
6  New York  2012    1500
7   Toronto  2012     500
8  New York  2016     500
9  New York  2018     300

After Sorting:
       City  Year  Points
5  Montreal  2012    1500
3  Montreal  2018    3000
4  Montreal  2018    2000
6  New York  2012    1500
8  New York  2016     500
9  New York  2018     300
7   Toronto  2012     500
2   Toronto  2018    3000
0   Toronto  2020    1000
1   Toronto  2020    2000

After Cumulative Sum:
       City  Year  Points  Points_cum
5  Montreal  2012    1500        1500
3  Montreal  2018    3000        3000
4  Montreal  2018    2000        5000
6  New York  2012    1500        1500
8  New York  2016     500         500
9  New York  2018     300         300
7   Toronto  2012     500         500
2   Toronto  2018    3000        3000
0   Toronto  2020    1000        1000
1

In [180]:
# 131. Find any matching value

print('Task 131:')

users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa']
}) 

print('Original Dataframe:')
print(users)

print('\nFinding `Montreal` in any cell :')
print(users[users.eq('Montreal').any(1)])

Task 131:
Original Dataframe:
    name      city
0  kevin   Toronto
1  james  Montreal
2  kumar   Calgary
3  kevin  Montreal
4  kevin  Montreal
5  james    Ottawa

Finding `Montreal` in any cell :
    name      city
1  james  Montreal
3  kevin  Montreal
4  kevin  Montreal


In [181]:
# 132. Add prefix on column lables

import pandas as pd
import numpy as np

np.random.seed(34)

df = pd.DataFrame(np.random.rand(30, 5)).add_prefix("feature_")
df["year"] = np.repeat(["2012", "2013", "2014"], 10)

print(df.head())
print(len(df))

   feature_0  feature_1  feature_2  feature_3  feature_4  year
0   0.038562   0.780100   0.092704   0.632893   0.013891  2012
1   0.936159   0.426574   0.253086   0.189965   0.414825  2012
2   0.013421   0.648473   0.869369   0.609036   0.807993  2012
3   0.826511   0.271683   0.836476   0.282541   0.138309  2012
4   0.714720   0.472537   0.556588   0.385576   0.941147  2012
30


In [182]:
# 133. Set values on where condition

df = pd.DataFrame({'city': ['Toronto', 'Toronto', 'Montreal', 'Montreal', 'Montreal'], 'Year': [2017, 2018, 2019, 2020, 2021]})

print('Original;')
print(df)

df['airport'] = None
df['airport'] = np.where(df['city'] == 'Toronto', {'airport_count': 2}, df['airport'])

print('\nAfter:')
print(df)

Original;
       city  Year
0   Toronto  2017
1   Toronto  2018
2  Montreal  2019
3  Montreal  2020
4  Montreal  2021

After:
       city  Year               airport
0   Toronto  2017  {'airport_count': 2}
1   Toronto  2018  {'airport_count': 2}
2  Montreal  2019                  None
3  Montreal  2020                  None
4  Montreal  2021                  None


In [183]:
# 135. Using transform

df = pd.DataFrame({
        'ID': [1, 2, 2, 3, 3, 4, 4],
        'Value': [10, 5, 5, 10, 4, 11, 12]
    })

df['Count'] = df.groupby('ID')['Value'].transform('count')
print(df)

   ID  Value  Count
0   1     10      1
1   2      5      2
2   2      5      2
3   3     10      2
4   3      4      2
5   4     11      2
6   4     12      2


In [184]:
# 136. Summing all elements

df = pd.DataFrame({
        'ID': [1, 2, 2, 3, 3, 4, 4],
        'Value': [10, 5, 5, 10, 4, 11, 12]
    })

sum1 = df.stack().sum()
print(sum1)

sum2 = df.to_numpy().sum()
print(sum2)

76
76


In [186]:
# # 137. Combine multiple CSV files by using Dask

# import dask.dataframe as dd

# df = dd.read_csv('/kaggle/input/rj-sample-datasets/transaction-*.csv')

# df = df.compute() 

# df.columns = ['Date', 'Description', 'Spent']

# df.head(2)

In [187]:
# 138. Separate Elements into Bins

df = pd.DataFrame({'number': np.random.randint(1, 100, 5)}) 
print('Original:')
print(df)

df['bins'] = pd.cut(x = df['number'], bins = [1, 20, 40, 60, 80, 100]) 
print('\nAfter pandas cut:')
print(df)

Original:
   number
0      80
1      81
2      38
3      83
4      47

After pandas cut:
   number       bins
0      80   (60, 80]
1      81  (80, 100]
2      38   (20, 40]
3      83  (80, 100]
4      47   (40, 60]


In [188]:
# 139. Encode the object as enumerated or categorical

codes, uniques = pd.factorize(['TO', 'NY', 'CA', 'MNT', 'CA', 'NY'], sort = True)

print(codes)
print(uniques)

[3 2 0 1 0 2]
['CA' 'MNT' 'NY' 'TO']


In [189]:
# 140. 


df = pd.read_csv("/kaggle/input/rj-sample-datasets/sample-transaction.csv", names = ['date', 'description', 'spent'])

# df

bins = np.linspace(min(df['spent']), max(df['spent']), 4)
# print(bins)
groupNames = ["low", "med", "high"]

df['spentGroup'] = pd.cut(df['spent'], bins, labels = groupNames, include_lowest = True)
print(df)

FileNotFoundError: [Errno 2] File /kaggle/input/rj-sample-datasets/sample-transaction.csv does not exist: '/kaggle/input/rj-sample-datasets/sample-transaction.csv'

In [190]:
# 141. Simple result table with Pandas

results = pd.DataFrame(columns = ['Accuracy'])

results.loc['Random Classifier'] = 98.893
results.loc['KNN'] = 99.343

results

Accuracy
Random Classifier    98.893
KNN                  99.343

In [191]:
# 142. isin with multiple conditions

df = pd.DataFrame([
        ['LEhOc7XSE0','2020', '03', 'car'],
        ['LEhOc7XSE0','2020', '03', 'truck'],
        ['LEhOc7XSE0','2020', '03', 'bike'],
        ['LEhOc7XSE0','2020', '03', 'insurance'],
        ['LEhOc7XSE0','2020', '03', 'inspection'],
        ['iXC5AfJMox','2020', '04', 'car'],
        ['iXC5AfJMox','2020', '04', 'truck'],
        ['iXC5AfJMox','2020', '04', 'inspection'],
        ['XpLLAySojz','2020', '01', 'bike'],
    ], columns=['order_id','year', 'month', 'item_type'])
print('Original:')
print(df)

df['bike_or_car'] = df['item_type'].isin({'bike', 'car'})
print('\nAfter:')
print(df)


Original:
     order_id  year month   item_type
0  LEhOc7XSE0  2020    03         car
1  LEhOc7XSE0  2020    03       truck
2  LEhOc7XSE0  2020    03        bike
3  LEhOc7XSE0  2020    03   insurance
4  LEhOc7XSE0  2020    03  inspection
5  iXC5AfJMox  2020    04         car
6  iXC5AfJMox  2020    04       truck
7  iXC5AfJMox  2020    04  inspection
8  XpLLAySojz  2020    01        bike

After:
     order_id  year month   item_type  bike_or_car
0  LEhOc7XSE0  2020    03         car         True
1  LEhOc7XSE0  2020    03       truck        False
2  LEhOc7XSE0  2020    03        bike         True
3  LEhOc7XSE0  2020    03   insurance        False
4  LEhOc7XSE0  2020    03  inspection        False
5  iXC5AfJMox  2020    04         car         True
6  iXC5AfJMox  2020    04       truck        False
7  iXC5AfJMox  2020    04  inspection        False
8  XpLLAySojz  2020    01        bike         True


In [192]:
# 143. String to Pandas with python engine and separator

from io import StringIO
import pandas as pd

data = '''            student       science   maths  history
0     David       90          100  89
20    Kevin       98          97  90
'''
df = pd.read_csv(StringIO(data), sep='\s\s+', engine='python')

print(df)

   student  science  maths  history
0    David       90    100       89
20   Kevin       98     97       90


In [193]:
# 144.

def get_unique_items(df):
    
    # how many cols are there
    cols = df.columns
    cols_count = len(df.columns)
    # print(cols_count)

    unique_max_count = 0
    for _col in cols:
#         print(_col)
        current_col_unique_values = list(df[_col].unique())
        list_len = len(current_col_unique_values) 
        
        if(list_len > unique_max_count):
            unique_max_count = list_len
    
    # list of each_cols and unique values
    col_unique_values = {}
    
    for _col in cols:
#         print(_col)
        current_col_unique_values = list(df[_col].unique())
        list_len = len(current_col_unique_values) 
        
        fill_count = 0
        if(list_len < unique_max_count):
            fill_count = unique_max_count - list_len
            
            for _ in range(fill_count):
                current_col_unique_values.append('-')
        
        col_unique_values[_col] = current_col_unique_values
        
    df_new = pd.DataFrame(col_unique_values)
    
    return df_new

users = pd.DataFrame({
    "name": ['kevin', 'james', 'kumar', 'kevin', 'kevin', 'james'], 
    "city": ['Toronto', 'Montreal', 'Calgary', 'Montreal', 'Montreal', 'Ottawa'],
    "count" : [7, 8, 9, 2, 7, 8] 
    
}) 

unique_user_items = get_unique_items(users)

unique_user_items

name      city  count
0  kevin   Toronto      7
1  james  Montreal      8
2  kumar   Calgary      9
3      -    Ottawa      2